# Generated by Django 4.2.1 on 2023-08-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_id', models.IntegerField()),
                ('Doctor', models.CharField(max_length=100)),
                ('Specialization', models.CharField(max_length=100)),
                ('Salary', models.IntegerField()),
                ('Experience', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tbl_hospital',
            },
        ),
    ]
