# Generated by Django 4.2.2 on 2023-08-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('date', models.DateField(max_length=30)),
                ('gender', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_patient',
            },
        ),
    ]
